[project]
name = "msc-xai-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.0.0",
    "keras>=3.7.0",
    "numpy>=2.0.2",
    "tensorflow>=2.18.0",
    "tqdm>=4.67.1",
    "wandb>=0.19.1",
]
